/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IRCClient_OnChannelListener */

#ifndef _Included_IRCClient_OnChannelListener
#define _Included_IRCClient_OnChannelListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
