/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IRCClient_OnConnectListener */

#ifndef _Included_IRCClient_OnConnectListener
#define _Included_IRCClient_OnConnectListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
