/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IRCClient */

#ifndef _Included_IRCClient
#define _Included_IRCClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IRCClient
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IRCClient_initialize
  (JNIEnv *, jobject);

/*
 * Class:     IRCClient
 * Method:    connect
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_IRCClient_connect
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring, jstring);

/*
 * Class:     IRCClient
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IRCClient_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     IRCClient
 * Method:    join
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_IRCClient_join
  (JNIEnv *, jobject, jstring);

/*
 * Class:     IRCClient
 * Method:    message
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_IRCClient_message
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
